# Configuration for Adversarial Training Reward Model

data:
  tokenizer: null
  train_files: ~/data/evalplus/train.parquet
  val_files: ~/data/evalplus/test.parquet
  prompt_key: prompt
  max_prompt_length: 1024
  max_response_length: 1024
  train_batch_size: 128
  return_raw_input_ids: False
  return_raw_chat: False
  shuffle: True
  filter_overlong_prompts: False
  truncation: left
  image_key: images
  custom_cls:
    path: null
    name: null

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: ~/models/code-llama-7b-base
    external_lib: null
    override_config: {}
    enable_gradient_checkpointing: True
    use_remove_padding: False
  actor:
    strategy: fsdp
    ppo_mini_batch_size: 64
    ppo_micro_batch_size_per_gpu: 4
    use_dynamic_bsz: True
    ppo_max_token_len_per_gpu: 16384
    grad_clip: 1.0
    clip_ratio: 0.2
    entropy_coeff: 0.001
    use_kl_loss: True
    use_torch_compile: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    ppo_epochs: 1
    shuffle: False
    ulysses_sequence_parallel_size: 1
    optim:
      lr: 5e-7
      lr_warmup_steps: -1
      lr_warmup_steps_ratio: 0.05
      min_lr_ratio: 0.1
      warmup_style: cosine
      total_training_steps: -1
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: False
      optimizer_offload: False
      fsdp_size: -1
    checkpoint:
      contents: ['model', 'optimizer', 'extra']
  ref:
    fsdp_config:
      param_offload: True
      wrap_policy:
        min_num_params: 0
    log_prob_micro_batch_size_per_gpu: 8
    log_prob_use_dynamic_bsz: True
    log_prob_max_token_len_per_gpu: 16384
    ulysses_sequence_parallel_size: 1
  rollout:
    name: vllm
    temperature: 0.8
    top_k: 50
    top_p: 0.95
    prompt_length: 1024
    response_length: 1024
    dtype: bfloat16
    gpu_memory_utilization: 0.7
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 1
    max_num_batched_tokens: 8192
    max_num_seqs: 512
    log_prob_micro_batch_size_per_gpu: 8
    log_prob_use_dynamic_bsz: True
    log_prob_max_token_len_per_gpu: 16384
    do_sample: True
    n: 1

reward_model:
  enable: True
  model:
    input_tokenizer: ${actor_rollout_ref.model.path}
    path: ~/models/code-reward-model
    external_lib: ${actor_rollout_ref.model.external_lib}
    fsdp_config:
      min_num_params: 0
      param_offload: False
  micro_batch_size_per_gpu: 8
  max_length: null
  reward_manager: prime

custom_reward_function:
  path: adversarial-training/train_reward/reward_function.py
  name: compute_score

algorithm:
  gamma: 1.0
  lam: 0.95
  adv_estimator: gae
  use_kl_in_reward: True
  kl_penalty: kl
  kl_ctrl:
    type: adaptive
    kl_coef: 0.01
    horizon: 10000
    target_kl: 0.1

trainer:
  total_epochs: 20
  project_name: adversarial_training
  experiment_name: evalplus_reward
  logger: ['console', 'wandb']
  log_val_generations: 5
  nnodes: 1
  n_gpus_per_node: 8
  save_freq: 5
  val_before_train: True
  test_freq: 2
  critic_warmup: 2
  default_hdfs_dir: ~/experiments/adversarial-training/${trainer.experiment_name}
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}
  resume_mode: auto
  resume_from_path: null
  remove_previous_ckpt_in_save: False
  del_local_ckpt_after_load: False
